# Generated by Django 5.2.8 on 2025-12-01 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FreshItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_label', models.CharField(help_text='What you want to show like "$7.99" or "From $6.49".', max_length=50)),
                ('category', models.CharField(choices=[('subs', 'Subs'), ('wraps', 'Wraps'), ('salads', 'Salads'), ('soups', 'Soups')], default='subs', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Product photo shown in Fresh Food list & detail.', null=True, upload_to='fresh_items/')),
                ('breads', models.JSONField(blank=True, default=list)),
                ('cheeses', models.JSONField(blank=True, default=list)),
                ('meats', models.JSONField(blank=True, default=list)),
                ('toppings', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, help_text='Leave empty to show in ALL stores.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fresh_items', to='core.store')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='deals/')),
                ('segment', models.CharField(choices=[('deal', 'Deal'), ('redeem', 'Redeem'), ('my', 'My Rewards')], default='deal', max_length=20)),
                ('category', models.CharField(choices=[('all', 'All'), ('combos', 'Combos'), ('drinks', 'Drinks'), ('energy', 'Energy'), ('snacks', 'Snacks'), ('bakery', 'Bakery'), ('candy', 'Candy'), ('more', 'More Deals')], default='all', max_length=20)),
                ('points_required', models.PositiveIntegerField(blank=True, null=True)),
                ('show_on_home', models.BooleanField(default=False, help_text="If checked, this can appear in the Home 'Deals for you' list.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
