# Generated by Django 5.2.8 on 2025-12-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text="If checked, can appear in Home 'Deals for you'."),
        ),
    ]
